[project]
name = "audio-merge"
version = "0.1.0"
description = "Project to merge audio files"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "pydub>=0.25.1",
    "tqdm>=4.67.1",
]
